# Generated by Django 4.0.4 on 2022-05-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0002_product_product_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_icon',
            field=models.ImageField(upload_to='#'),
        ),
    ]
