# Generated by Django 4.0.4 on 2022-05-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0005_alter_product_product_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cprod_size',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
