# Generated by Django 4.0.4 on 2022-05-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0006_usercart_cprod_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cproduct_cat',
            field=models.CharField(default=0, max_length=30),
        ),
    ]
