# Generated by Django 4.0.4 on 2022-05-22 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagro', '0008_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='oproduct_desc',
        ),
    ]
